### PR TITLE
change Email to verify email against Case insensitive 

### PR DESCRIPTION
**Pull request by sriramHaven**
This is the fix for Email verification by Pin. When the right pin is passed by the user to confirm the email change, the new Email has to update the login email.

### CODE REVIEW

**Comment by selsamman** [comment]
I don't think this fix is correct.  This code is called from a number of places not all of which you would want to take in a new email address from the controller's newEmail property.  The sequence for changing an email is to call changeEmail.  You are authenticated as part of that call and if the deferEmail config option is on the principal's newEmail field will be filled in and the principal's email field remains as it was.  A verification code is setup and later you can call publicLoginWithNewEmail. There you pass in the new email in the controller's email field and you are authenticated based on this new new email address.  Once authenticated the principals email is set to the controller's email address (which was just authenticated)

**Comment by sriramHaven** [comment]
PublicLoginWithNewEmail gets triggered on a action of modal sign in . Currently , We show this modal as a result of user clicking Verifiy email . But the case we are talking about is the one by PIN verification . It will be a design flaw if we ask user to login back with new email even after they have inputted correct PIN and click get my decision . 

What is the case you are thinking of which passes newEmail and still not update the login email in PINVerification function ?

**Comment by selsamman** [comment]
So this is a case where the user has changed his email, is still logged in and wants to present the verification code to effect the email change.  There is no function in userman for this.  Instead you need to call privateVerifyEmailFromCode to validate and consume the code you pass as a parameter and then just change the email property to the new email.

**Comment by sriramHaven** [comment]
Correct.  privateVerifyEmailFromCode is what being called and which in turn calls `consumeEmailVerificationCode` from userman. It still does not work .Thats why adding the fix in `consumeEmailVerificationCode`

**Comment by selsamman** [comment]
You need to update the email in the application code.

**Comment by sriramHaven** [comment]
added the fix for change email - which does not validate existing email records with case insensitive search. We do case insenstive checks against existing records during register email process .

**Pull request merged**
